baseURL = "https://uk-dave.com/"
languageCode = "en-gb"
title = "David Bull"
theme = "ukdave"

googleAnalytics = "G-N7WYC3EZLL"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.parser.attribute]
  block = true

[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false

[build.buildStats]
  enable = true

[params]
  author = "David Bull"
  theme = "dark"
  favicon = "/img/favicon.ico"
  logo = "/img/weemee-head-only_200x200.png"
  strapline = "Software Developer, Amateur Photographer, Geek"
  description = "My personal website"

[params.social]
  GitHub        = "ukdave"
  Email         = "david@uk-dave.com"
  Twitter       = "ukdave"
  LinkedIn      = "david-bull-51810016"
  # StackOverflow = "username"
  Exercism      = "ukdave"
  Flickr        = "uk_dave"

[[menu.main]]
  name = "Blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "Projects"
  weight = 200
  identifier = "projects"
  url = "/projects/"
[[menu.main]]
  name = "Photography"
  weight = 300
  identifier = "photography"
  url = "/photography/"
