baseURL = "https://uk-dave.com/"
languageCode = "en-gb"
title = "David Bull"
theme = "ukdave"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false

[build]
  writeStats = true

[params]
  author = "David Bull"
  logo = "weemee-head-only_200x200.png"
  strapline = "Software Developer, Amateur Photographer, Geek"

[params.social]
  GitHub        = "ukdave"
  Email         = "david@uk-dave.com"
  Twitter       = "ukdave"
  LinkedIn      = "david-bull-51810016"
  # StackOverflow = "username"
  Flickr        = "uk_dave"

[[menu.main]]
  name = "Blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "Projects"
  weight = 200
  identifier = "projects"
  url = "/projects/"
