[build]
publish = "public"
command = "hugo --gc --minify -d public"


[context.production.environment]
HUGO_VERSION = "0.84.0"
HUGO_ENV = "production"


[context.deploy-preview]
command = "hugo --gc --minify -d public --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.84.0"


[context.branch-deploy]
command = "hugo --gc --minify -d public -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.84.0"
